version: '2'
services:
  app:
    build: .
    volumes:
     - .:/code
    depends_on:
     - "postgres"
    environment:
     - VIGIL_FROM_ADDRESS
     - VIGIL_USERNAME
     - VIGIL_PORT
     - VIGIL_HOST
     - VIGIL_FROM_NAME
     - VIGIL_PASSWORD
     - VIGIL_TO
     - POSTGRES_HOST
     - POSTGRES_PORT
     - POSTGRES_USER
     - VIGIL_DB

    container_name: vigil_app
  postgres:
    image: "postgres:9.6"
    container_name: vigil_postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER
     - POSTGRES_PASSWORD
