version: '2'
services:
  app:
    build: .
    volumes:
     - .:/code
    depends_on:
     - "postgres"
    environment:
     - VIGIL_FROM_ADDRESS
     - VIGIL_USERNAME
     - VIGIL_PORT
     - VIGIL_HOST
     - VIGIL_FROM_NAME
     - VIGIL_PASSWORD
     - VIGIL_TO

    container_name: vigil_app
  postgres:
    image: "postgres:9.5"
    container_name: vigil_postgres